language: generic
sudo: required

install:
  - sudo apt-get -y install texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra
  # conda
  - wget -c --no-check-certificate https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -P /tmp
  - bash /tmp/Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --add channels conda-forge
  - conda install -y openturns pyfmi sphinx nose numpydoc flake8 omcompiler

script:
  - flake8 . --exit-zero
  - ./mo2fmu.sh ./otfmi/example/file/deviation.mo ./otfmi/example/file/fmu/linux64/deviation.fmu
  - nosetests --nocapture
  - python setup.py install
  - pushd doc && make html BUILDDIR=~/.local/share/otfmi/doc && popd
  # run tests in py2.7
  - conda create -y -n py27 python=2.7
  - source activate py27
  - conda install -y openturns pyfmi nose
  - nosetests --nocapture

after_success:
  - test "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" || exit 0
  - git clone https://${GH_TOKEN}@github.com/openturns/openturns.github.io.git
  - REPO_NAME=`echo "${TRAVIS_REPO_SLUG}" | cut -d "/" -f 2`
  - mkdir -p openturns.github.io/${REPO_NAME}/${TRAVIS_BRANCH}
  - cp -r ~/.local/share/${REPO_NAME}/doc/html/* openturns.github.io/${REPO_NAME}/${TRAVIS_BRANCH}
  - cd openturns.github.io
  - touch .nojekyll
  - git config user.email "support@travis-ci.com"
  - git config user.name "Travis CI"
  - git add -A .
  - git commit -a -m "Travis build ${REPO_NAME} ${TRAVIS_BUILD_NUMBER}"
  - git push --quiet origin master > /dev/null 2>&1

env:
  global:
    secure: "exGxIfCYRlG/1NTXn4kLRjySrT5HnaLOj9WxkwaXosaxGzcifcXy41chEXT/P8IoQrveRDtJLMJjSwgWXJUss36Fn4JoD5qBLW5DxE4Y5vCihM7jsmAtfobODyOPEQQPs9ej8y8lJNDU+yO1ibEloO7rDJd+JKnoh9UkcoVbvrTUDK8NMN3O42jWYdt7e8Yi/mMYVeNJoyHndrFdTMtcL5gsQtqNaE8PQctytULtjgoioK+7SG1PQJ4TUg3I9Hb4ke4beAGNxTMpUt/dg1U1igmtdi8gLUJw2KG4xUGlfXrR/+GlYHmw38AMtxv4Rk11tu32cNgeDXzBJAdJfg9Nv8qImCcXhXNLDT//43iid1u/ZSxUVyAYcQ5XmKHO1IgFEULVLTucZI7TlN8AWOP1fyhBJIWNsqQva4V+/yyH6w6tKGZzOb5bl/a4JSdotKmyG7QuqAp5iiHRptt0k0JcemMCXW6IBW3TdYTb2zj3OzaWbjy89cXoldZNdusov4m1Ru3Fvk5djaVHmVo20yEWeUY8IfA6EsbJ2YJOwCyce1W/L+Mdr8l/ra8StzQxQ+vVxtc+jlH71R5WvMyiWRBswXws9uTL1hK3eJhrZHmXcYTFTHlp3y833jTez1MVbRZYcBtMPRxMMLBp2rAFY/1HsEniiuUGtkNcArBBqWtIf9k="
