install:
  - appveyor-retry appveyor DownloadFile https://repo.continuum.io/miniconda/Miniconda2-latest-Windows-x86.exe
  - start /wait "" Miniconda2-latest-Windows-x86.exe /InstallationType=JustMe /AddToPath=0 /RegisterPython=0 /S /D=C:\Libraries\miniconda
  - set PATH=%PATH%;C:\Libraries\miniconda;C:\Libraries\miniconda\Scripts
  - conda install -y -c conda-forge pyfmi openturns nose

build_script:
  - nosetests --nocapture
