install:
  # omc
  - choco install openmodelica --version=1.17.0
  - set PATH=%PATH%;C:\Program Files\OpenModelica1.17.0-64bit\bin
  - omc --version
  # conda
  - curl -fSsLO https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe
  - set CONDA_ROOT="%UserProfile%\Miniforge3"
  - Miniforge3-Windows-x86_64.exe /InstallationType=JustMe /S /D=%CONDA_ROOT%
  - call %CONDA_ROOT%\Scripts\activate.bat
  - conda install -y pyfmi openturns dill nose

build_script:
  - nosetests --nocapture
