install:
  - set PATH=C:\Miniconda36;C:\Miniconda36\Scripts;%PATH%
  - conda config --add channels conda-forge
  - conda update -y conda
  - conda update -y --all
  - conda install -y matplotlib
  - python -c "import tornado"
  - python -c "import matplotlib.pyplot as plt"

build_script:
  - nosetests --nocapture
  # run tests with py2.7
  - conda create -y -n py27 python=2.7
  - activate py27
  - conda install -y pyfmi openturns nose
  - nosetests --nocapture
