install:
  - set PATH=%PATH%;C:\Miniconda36-x64;C:\Miniconda36-x64\Scripts
  - conda config --add channels conda-forge
  - conda install -y pyagrum
  - python bug41.py
  - conda install -y pyfmi openturns nose

build_script:
  - nosetests --nocapture
  # run tests with py2.7
  - conda create -y -n py27 python=2.7
  - activate py27
  - conda install -y pyfmi openturns nose
  - nosetests --nocapture
